" 🅲 🅷 🅰 🅽 🅳 🅴 🆁
" ---------------------------------------------------------
" VIM editor preferences

set nocompatible    " Don't try to be Vi compatible
set number          " Show line number
set incsearch       " Search as you type - incremental
set ignorecase      " Ignore case when searching
set hlsearch        " Highlight search matches
set showmatch       " Match brackets 

" Status bar section
" ---------------------------------------------------------
set laststatus=2    " Enable status bar

set statusline =%7*[%n]%*
set statusline +=%1*%F\ %*%8*%m%r%*%1*%h%w%* "filename
set statusline +=%7*\|%*
set statusline+=%2*\ %Y: "filetype
set statusline+=%{&ff}:  "dos/unix
set statusline+=%{&fenc!=''?&fenc:&enc}\ %* "encoding
set statusline +=%7*\|%*
set statusline+=%2*\ row:%l/%*%1*%L%*%2*\ %2*\ \col:%v\ %*
set statusline +=%7*\|%*
set statusline+=%2*\ ASCII:%b\ %*  " ascii
set statusline +=%7*\|%*

" XDG section
" ---------------------------------------------------------
" Use XDG defaults if not exported 
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME . '/.local/state'
endif

" Ensure the directory exists
call mkdir($XDG_STATE_HOME . '/vim', 'p', 0700)

" Tell Vim where to write viminfo
if has('viminfo')
  let &viminfofile = $XDG_STATE_HOME . '/vim/viminfo'
endif
