[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = wMyOjCOnJLOTTa12TT1W1DJLfMOBsvkQ80bIGfj7XW4=
MTU = 1420

# Open the UDP port for incoming connections
PostUp = iptables -I INPUT -p udp --dport 51820 -j ACCEPT

# Allow traffic to flow through the VPN (Forwarding)
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -I FORWARD -o wg0 -j ACCEPT

# Enable the "Magic" NAT (Internet access for clients)
PostUp = iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE

[Peer]
PublicKey = BaLCw8rNJz3c3d/TXC7xVtEoBJBSWEjnLm4p4Vm9ejo=
AllowedIPs = 10.8.0.2/32
